// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string     `json:"id"`
	PostID    string     `json:"postId"`
	Sender    *User      `json:"sender"`
	ReplyTo   *Comment   `json:"replyTo,omitempty"`
	Text      string     `json:"text"`
	CreatedAt string     `json:"createdAt"`
	Replies   []*Comment `json:"replies,omitempty"`
}

type Mutation struct {
}

type NewComment struct {
	PostID   string  `json:"postID"`
	SenderID string  `json:"senderID"`
	ReplyTo  *string `json:"replyTo,omitempty"`
	Text     string  `json:"text"`
}

type NewPost struct {
	Title                 string `json:"title"`
	Text                  string `json:"text"`
	IsCommentingAvailable *bool  `json:"isCommentingAvailable,omitempty"`
	UserID                string `json:"userId"`
}

type Post struct {
	ID                    string     `json:"id"`
	Title                 string     `json:"title"`
	Text                  string     `json:"text"`
	CreatedBy             *User      `json:"createdBy"`
	CreatedAt             string     `json:"createdAt"`
	IsCommentingAvailable bool       `json:"isCommentingAvailable"`
	Comments              []*Comment `json:"comments,omitempty"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}
